"""Native field layout for the supported UNI2 executable.

These are offsets within immutable entity snapshots, not a memory-scan recipe.
The injected DLL validates the executable and supplies all module-relative
runtime locations through the shared-memory header.
"""
from __future__ import annotations

ENTITY_STRIDE = 0xBC0
ENTITY_COUNT = 12
MAX_OBJECTS = 2000
PLAYER_OFFSET = 0x434
ACTIVE_OFFSET = 0x7D8
ANIMATION_OFFSET = 0x654
DESCRIPTOR_OFFSET = 0x650
ATTACK_OFFSET = 0x658
MOVABLE_OFFSET = 0x43C
LANDING_LOCK_OFFSET = 0x448
SECOND_MOVABLE_OFFSET = 0x44C
SECOND_TIMER_OFFSET = 0x458
OVERRIDE_STATUS_OFFSET = 0x45C
OVERRIDE_TIMER_OFFSET = 0x468
DYNAMIC_FLAGS_OFFSET = 0x47C
DYNAMIC_TIMER_OFFSET = 0x488
STRIKE_TIMERS = (0x200, 0x202)
THROW_TIMERS = (0x201, 0x203)
MOVE_CODE_OFFSET = 0x6B8
ACTION_FRAME_OFFSET = 0x680
ACTION_INSTANCE_OFFSET = 0x68C
GUARD_PLUS_OFFSET = 0x64A
HIT_FILTER_OFFSET = 0x49C
HIT_FILTER_TIMER_OFFSET = 0x4A8
ATTACK_FILTER_OFFSET = 0x4AC
HITSTOP_OFFSET = 0x1DE
LABEL_OFFSET = 0xAE8
LABEL_BYTES = 64
PARENT_POINTER_OFFSET = 0x3F4
OBJECT_READ_SIZE = 0x7DC
# Special chunk identifier for native object summaries; never dereferenced.
OBJECT_SUMMARY_ADDRESS = 0xFF000000
OBJECT_SUMMARY_WORDS = 12

PHASE_STATE_OFFSET = 0x5A4B2C
SLOW_SKIP_OFFSET = 0x657E78
GLOBAL_STOP_OFFSET = 0x657E80
SCENE_CLOCK_OFFSET = 0x5A58C0
